### ISSUE TITLE
Claim addon causing server crash and lag with griefprevention.

### ISSUE THREAD

**Issue by matipoirierg** [BillyGalbreath/Pl3xMap-Claims#1]
I asked on GP github and this was the answer: "GP could do a little better here, but there's no reason for a map addon to have to look up player names on the main thread via GP to formulate popups for a web server. Contact the author of the addon and ask them to convert UUIDs to names asynchronously."
git-Purpur-1990 (MC: 1.20)*
Pl3xMap version 1.20-441
Pl3xMap Claims 1.20-23
https://spark.lucko.me/ckTP2GUleG
Crash error: https://mclo.gs/uMkV8U5

**Comment by matipoirierg** [comment]
Tried latest and it's still performing bad but at least the server is not crashing. https://spark.lucko.me/RL0OH1cCEM
When I was using the old gp addon (addonds folder) that came when you build pl3xmap the issue was not happening, is this old add-on still possible to get build pl3xmap?

**Comment by BillyGalbreath** [comment]
```
[21:18:57] [Watchdog Thread/ERROR]: GriefPrevention.jar//me.ryanhamshire.GriefPrevention.Claim.getOwnerName(Claim.java:759)
[21:18:57] [Watchdog Thread/ERROR]: Pl3xMap-Claims-1.20-23.jar//net.pl3x.map.claims.hook.griefprevention.GriefPreventionClaim.getOwnerName(GriefPreventionClaim.java:62)
```
I use the exact same API call, the exact same way..

Current code in this project
https://github.com/BillyGalbreath/Pl3xMap-Claims/blob/master/src/main/java/net/pl3x/map/claims/hook/griefprevention/GriefPreventionHook.java#LL100C49-L100C49

Old code from the addon you are referring to
https://github.com/BillyGalbreath/Pl3xMap/blob/v2/addons/griefprevention/src/main/java/net/pl3x/map/addon/griefprevention/hook/GPHook.java#L49

Edit: Also, I'm not seeing any lag from your spark report.. What makes you think it is lagging? https://spark.lucko.me/RL0OH1cCEM

![image](https://github.com/BillyGalbreath/Pl3xMap-Claims/assets/332527/73688661-3ee4-4756-b7aa-1411fdb1891a)

The report was running for 13m 20s. That's a total of 16000 ticks (since your report shows a solid 20 tps).

There are only 14 ticks that went over the threshold of 300ms, out of a grand total of 16000.

When we break those 14 ticks down, we see less than 6s (out of 13m 20s) was spent on GriefPrevention API calls..

![image](https://github.com/BillyGalbreath/Pl3xMap-Claims/assets/332527/58f3df04-31af-448f-9441-8038ae023154)

So where is this bad performance you keep reporting?
